package com.sample

import com.sample.GUI
 
declare Question
	question : String
	answer : String
end

//        	function void askQuestion(Question q){ - don't know why it doesn't work and how to make function
//        		GUI gui = new GUI();
//        		gui.window("Which genre interest you?", options);
//        	}

rule "Which genre interest you?"
	when
	then
		String[] options = {"Medieval Fantasy", "Far Future",
   				 "Mecha", "Generes related to near present",
   				 "Westerns", "Supers", "Other Alternate History",
   				 "Genre Shouldn't matter"};
	 	// Receive answer from gui and assign it to q
	   	GUI gui = new GUI();
	   	String answer = gui.window("Which genre interest you?", options); 
	   	System.out.println( answer );
	   	Question q = new Question("Which genre interest you?", answer);
   		insert(q);
end

rule "Which subgenre?"
	when
		$q : Question(question == "Which genre interest you?", answer == "Medieval Fantasy")
	then
		String[] options = {"Oriental", "Humor", "High Fantasy/General", "High magic", "Low Fantasy"};
	 
	   	GUI gui = new GUI();
	   	String answer = gui.window("Which subgenre?", options);
	   	System.out.println( answer );
	   	Question q = new Question("Which subgenre?", answer);
   		insert(q);
end

rule "With meta-plots and CCG element?"
	when
		$q : Question(question == "Which subgenre?", answer == "Oriental")
	then
		String[] options = {"Yes", "No"};
	 
	   	GUI gui = new GUI();
	   	String answer = gui.window("With meta-plots and CCG element?", options);
	   	System.out.println( answer );
	   	Question q = new Question("With meta-plots and CCG element?", answer);
   		insert(q);
end




