package com.sample

import com.sample.GUI
 
declare Question
	question : String
	answer : String
end

function Question askQuestion(String q, String[] options) {
    GUI gui = new GUI();
    String answer = gui.window(q, options);
    System.out.println( answer );
    Question quest = new Question(q, answer);
   	return quest;
}

function void showAnswer(String ans) {
	GUI gui = new GUI();
    String answer = gui.window(ans, null);
    System.out.println( answer );
}


rule "Which genre interest you?"
	when
	then
		String[] options = {"Medieval Fantasy", "Far Future",
   				 "Mecha", "Generes related to near present",
   				 "Westerns", "Supers", "Other Alternate History",
   				 "Genre Shouldn't matter"};
	 	
	   	Question nextq = askQuestion("Which genre interest you?", options);
	   	insert(nextq);
end

rule "Which subgenre?"
	when
		$q : Question(question == "Which genre interest you?", answer == "Medieval Fantasy")
	then
		String[] options = {"Oriental", "Humor", "High Fantasy/General", "High magic", "Low Fantasy"};
	 
	   	Question nextq = askQuestion("Which subgenre?", options);
	   	insert(nextq);
end

rule "With meta-plots and CCG element?"
	when
		$q : Question(question == "Which subgenre?", answer == "Oriental")
	then
		String[] options = {"Yes", "No"};

	   	Question nextq = askQuestion("With meta-plots and CCG element?", options);
	   	insert(nextq);
end

rule "FATE based d20 based or neither?"
	when
		$q : Question(question == "Which genre interests you?", answer == "Other Alternate History")
	then
		String[] options = {"FATE", "d20", "Neither"};

	   	Question nextq = askQuestion("FATE based d20 based or neither?", options);
	   	insert(nextq);
end

rule "D20 Past"
	when
		$q : Question(question == "FATE based d20 based or neither?", answer == "d20")
	then
	 	showAnswer("D20 Past");
end

rule "Pick a subgenre"
	when
		$q : Question(question == "FATE based d20 based or neither?", answer == "Neither")
	then
		String[] options = {"Pulp", "Japanese/Samurai", "Mobsters 1930s"};

	   	Question nextq = askQuestion("Pick a subgenre", options);
	   	insert(nextq);
end

rule "Pulp"
	when
		$q : Question(question == "Pick a subgenre", answer == "Pulp")
	then
	 	showAnswer("Pulp");
end

rule "Bushido"
	when
		$q : Question(question == "Pick a subgenre", answer == "Japanese/Samurai")
	then
	 	showAnswer("Bushido");
end

rule "Gangbusters"
	when
		$q : Question(question == "Pick a subgenre", answer == "Mobsters 1930s")
	then
	 	showAnswer("Gangbusters");
end

rule "Supernatural or pulp?"
	when
		$q : Question(question == "FATE based d20 based or neither?", answer == "FATE")
	then
		String[] options = {"Pulp", "Supernatural"};

	   	Question nextq = askQuestion("Supernatural or pulp?", options);
	   	insert(nextq);
end

rule "Spirit of the Century"
	when
		$q : Question(question == "Supernatural or pulp?", answer == "Pulp")
	then
	 	showAnswer("Spirit of the Century");
end

rule "Dresden Files"
	when
		$q : Question(question == "Supernatural or pulp?", answer == "Supernatural")
	then
	 	showAnswer("Dresden Files");
end

rule "Genre really shouldn't matter?"
	when
		$q : Question(question == "Which genre interest you?", answer == "Genre Shouldn't matter")
	then
		String[] options = {"No, not really", "Yes"};

	   	Question nextq = askQuestion("Really?", options);
	   	insert(nextq);
end

rule "Which genre interest you? (again)"
	when
		$q : Question(question == "Genre really shouldn't matter?", answer == "No, not really")
	then
		String[] options = {"Medieval Fantasy", "Far Future",
   				 "Mecha", "Generes related to near present",
   				 "Westerns", "Supers", "Other Alternate History",
   				 "Genre Shouldn't matter"};
	 	
	   	Question nextq = askQuestion("Which genre interest you?", options);
	   	insert(nextq);
end

rule "What is du/dx = cu+xy?"
	when
		$q : Question(question == "Genre really shouldn't matter?", answer == "Yes")
	then
		String[] options = {"It should be +x, not +xy", "A differential equation", "Huh?"};

	   	Question nextq = askQuestion("What is du/dx = cu+xy?", options);
	   	insert(nextq);
end

rule "GURPS"
	when
		$q : Question(question == "What is du/dx = cu+xy?", answer == "It should be +x, not +xy")
	then
	 	showAnswer("GURPS");
end

rule "HERO"
	when
		$q : Question(question == "What is du/dx = cu+xy?", answer == "A differential equation")
	then
	 	showAnswer("HERO");
end

rule "Want an 'open' game?"
	when
		$q : Question(question == "What is du/dx = cu+xy?", answer == "Huh?")
	then
		String[] options = {"Doesn't matter", "No", "Yes"};

	   	Question nextq = askQuestion("Want an 'open' game?", options);
	   	insert(nextq);
end

rule "Open game really doesn't matter?"
	when
		$q : Question(question == "Want an 'open' game?", answer == "Doesn't matter")
	then
		String[] options = {"Sorta", "A fascist could make It for all I care"};

	   	Question nextq = askQuestion("Really?", options);
	   	insert(nextq);
end

rule "TORG"
	when
		$q : Question(question == "Open game really doesn't matter?", answer == "Sorta")
	then
	 	showAnswer("TORG");
end

rule "RIFTS / Savage Worlds"
	when
		$q : Question(question == "Open game really doesn't matter?",
					  answer == "A fascist could make It for all I care")
	then
	 	showAnswer("RIFTS");
		showAnswer("Savage Worlds");
end

rule "Savage Worlds"
	when
		$q : Question(question == "Want an 'open' game?", answer == "No")
	then
		showAnswer("Savage Worlds");
end

rule "Want one that is 'cinematic' or has a bit of humor?"
	when
		$q : Question(question == "Want an 'open' game?", answer == "Yes")
	then
		String[] options = {"Cinematic", "Humor", "None"};

	   	Question nextq = askQuestion("Want one that is 'cinematic' or has a bit of humor?", options);
	   	insert(nextq);
end

rule "Open d6"
	when
		$q : Question(question == "Want one that is 'cinematic' or has a bit of humor?", answer == "Cinematic")
	then
	 	showAnswer("Open d6");
end

rule "Risus"
	when
		$q : Question(question == "Want one that is 'cinematic' or has a bit of humor?", answer == "Humor")
	then
	 	showAnswer("Risus");
end

rule "Have a niche genre in mind?"
	when
		$q : Question(question == "Want one that is 'cinematic' or has a bit of humor?", answer == "None")
	then
		String[] options = {"No", "Super Natural Or pulp", "Super heroes"};

	   	Question nextq = askQuestion("Have a niche genre in mind?", options);
	   	insert(nextq);
end

rule "FUDGE"
	when
		$q : Question(question == "Have a niche genre in mind?", answer == "No")
	then
	 	showAnswer("FUDGE");
end

rule "ICONS (again)"
	when
		$q : Question(question == "Have a niche genre in mind?", answer == "Super heroes")
	then
		showAnswer("ICONS");
end

rule "Supernatural or pulp? (again)"
	when
		$q : Question(question == "Have a niche genre in mind?", answer == "Super Natural Or pulp")
	then
		String[] options = {"Pulp", "Supernatural"};

	   	Question nextq = askQuestion("Supernatural or pulp?", options);
	   	insert(nextq);
end

rule "Based on real comics?"
	when
		$q : Question(question == "Which genre interest you?", answer == "Supers")
	then
		String[] options = {"DC", "Marvel", "No or other"};

	   	Question nextq = askQuestion("Based on real comics?", options);
	   	insert(nextq);
end

rule "Want a diceless system or one with lots of online fansites?"
	when
		$q : Question(question == "Based on real comics?", answer == "Marvel")
	then
		String[] options = {"Diceless", "Online Fansites"};

	   	Question nextq = askQuestion("Want a diceless system or one with lots of online fansites?", options);
	   	insert(nextq);
end

rule "Marvel Universe"
	when
		$q : Question(question == "Want a diceless system or one with lots of online fansites?", answer == "Diceless")
	then
	 	showAnswer("Marvel Universe");
end

rule "Marvel SuperHeroes (FASERIP)"
	when
		$q : Question(question == "Want a diceless system or one with lots of online fansites?", answer == "Online Fansites")
	then
	 	showAnswer("Marvel SuperHeroes (FASERIP)");
end

rule "D6s, d10s or d20?"
	when
		$q : Question(question == "Based on real comics?", answer == "DC")
	then
		String[] options = {"D6", "D10", "D20"};

	   	Question nextq = askQuestion("D6s, d10s or d20?", options);
	   	insert(nextq);
end

rule "DC Universe"
	when
		$q : Question(question == "D6s, d10s or d20?", answer == "D6")
	then
	 	showAnswer("DC Universe");
end

rule "DC Heroes"
	when
		$q : Question(question == "D6s, d10s or d20?", answer == "D10")
	then
	 	showAnswer("DC Heroes");
end

rule "DC Adventures"
	when
		$q : Question(question == "D6s, d10s or d20?", answer == "D20")
	then
	 	showAnswer("DC Adventures");
end

rule "Do you like d20 (skills, feats, etc.)?"
	when
		$q : Question(question == "Based on real comics?", answer == "No or other")
	then
		String[] options = {"Yes", "No"};

	   	Question nextq = askQuestion("Do you like d20 (skills, feats, etc.)?", options);
	   	insert(nextq);
end

rule "Mutants and Mansterminds"
	when
		$q : Question(question == "Do you like d20 (skills, feats, etc.)?", answer == "Yes")
	then
	 	showAnswer("Mutants and Mansterminds");
end

rule "Do you like to point buy character gen?"
	when
		$q : Question(question == "Do you like d20 (skills, feats, etc.)?", answer == "No")
	then
		String[] options = {"Yes", "Yes, with fractions!", "Not Really"};

	   	Question nextq = askQuestion("Do you like to point buy character gen?", options);
	   	insert(nextq);
end

rule "GURPS Supers"
	when
		$q : Question(question == "Do you like to point buy character gen?", answer == "Yes, with fractions!")
	then
	 	showAnswer("GURPS Supers");
end

rule "Champions"
	when
		$q : Question(question == "Do you like to point buy character gen?", answer == "Yes")
	then
	 	showAnswer("Champions");
end

rule "ICONS"
	when
		$q : Question(question == "Do you like to point buy character gen?", answer == "Not Really")
	then
	 	showAnswer("ICONS");
end



